### ISSUE TITLE
Linux, asp, c# 

### ISSUE THREAD

**Issue by STONE-CHN** [hznulug/zhcp#1]

**Comment by STONE-CHN** [comment]
呃，真是奇怪的组合

**Comment by uwyc** [comment]
[Monodevelop](http://www.monodevelop.com/download/linux/)已经可以很好的代替Visual Studio了，而且也是微软支持的一个跨平台项目。
还有一个重要原因，因为涉及到office文档处理，特别是文字文档，我想用[Open XML SDK](https://github.com/OfficeDev/Open-XML-SDK)，但是，这些也不是一尘不变的，如果你有更好的建议或是解决方案，也可以提出来，方正还没开始呢。
